version: 2.1

orbs:
  node: circleci/node@1.1.6

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: yarn.lock
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: '14-browsers'
    environment:
      AWS_ACCESS_KEY_ID: 'fakeMyKeyId'
      AWS_SECRET_ACCESS_KEY: 'fakeMySecretKey'
    steps:
      - checkout
      - install_deps
      - run: yarn test
      - run: yarn type-check
      - run: yarn lint:ci
